### ISSUE TITLE
Unnecessary `console.log` in `formatFromMs()`?

### ISSUE THREAD

**Issue by baconandon** [seriousManual/hirestime#31]
Version 5.0.0 [added a console.log statement](https://github.com/seriousManual/hirestime/commit/fc9b130cf33958c4705c931bcca67b9e2776b628#diff-ed009b6b86b017532ef0489c77de5100R12) to `index.ts` that seems too chatty for the long-running performance-monitoring I am doing. Can it be removed?

**Comment by seriousManual** [comment]
Hey, thank you very much for the report!
Fixed in 5.0.6
