### ISSUE TITLE
v6.0.0 published by mistake?

### ISSUE THREAD

**Issue by osukaa** [seriousManual/hirestime#32]
Hello!

We use a tool to keep our dependencies up to date and today it showed v6 as available. 

It's also being reported in npm -> https://www.npmjs.com/package/hirestime

But I couldn't find release notes or the tag pushed to the repository.

I was wondering if it was published by mistake?

**Comment by seriousManual** [comment]
hey, thank you for the heads-up!
I forgot to push to the repo, done!
