### ISSUE TITLE
using from javascript?

### ISSUE THREAD

**Issue by bonesoul** [seriousManual/hirestime#33]
is it possible to use it directly from js after the typescript upgrade of the library?

**Comment by seriousManual** [comment]
Hello,
yes it is, the bundle is shipped as a transpiled version with optional type
files additionally.

Am Sa., 18. Juli 2020 um 02:45 Uhr schrieb Hüseyin Uslu <
notifications@github.com>:

**Comment by bonesoul** [comment]
any chances that we can  get it node compatible using stg. like; https://dev.to/charperbonaroo/creating-a-ts-written-npm-package-for-use-in-node-js-or-browser-5gm3

**Comment by seriousManual** [comment]
hi, I'm not sure i understand what you mean.
the module is shipped transpiled to js and can be integrated anyhwere you want to.

check it out on unpkg: https://unpkg.com/hirestime@6.1.0/dist/index.js

that's the compiled bundle that can be run anyhwere you like.

**Comment by bonesoul** [comment]
I was trying to use it with my backend node.js. Will check, thanks.
