### ISSUE TITLE
7.0.x: Subtypes not reachable in typescript imports

### ISSUE THREAD

**Issue by emzeidan** [seriousManual/hirestime#46]
After upgrading to 7.0.3, the typescript import for `Elapsor` (and all but the default) throws an error in ESLint:

```typescript
import { Elapsor } from 'hirestime/dist/hirestime';
```
Error:
> ESLint: Unable to resolve path to module 'hirestime/dist/hirestime'.(import/no-unresolved)

Should the `index.ts` (and therefore the built `index.d.ts`) be updated to
```typescript
import default hirestime from './hirestime';

export { 
  Elapsor, 
  hirestimeNode, 
  hiresTimeBrowserDate, 
  hiresTimeBrowserPerformance
} from './hirestime';

export default hirestime;
```

This would allow usage such as
```typescript
import hirestime, {Elapsor} from 'hirestime';
```

Thanks

**Comment by emzeidan** [comment]
Hi @seriousManual ! Would you be able to take a look at this Issue and the related PR, please?

**Comment by seriousManual** [comment]
Hi, thanks for reaching out, I'm not sure about the use case for this change?

**Comment by emzeidan** [comment]
Hi!

This is for projects using typescript with strong typing which need to include the `Elapsor` type.

At the moment, since it's not exported, we need these 2 lines:
```typescript
import timer from 'hirestime';
import { Elapsor } from 'hirestime/dist/hirestime';
```
But, the `Elapsor` type can't be resolved, so it needs to be eslint-ignored
```typescript
import timer from 'hirestime';
// eslint-disable-next-line import/no-unresolved
import { Elapsor } from 'hirestime/dist/hirestime';
```

This change allows the imports to be resolved without error. 

I hope that makes sense.

**Comment by seriousManual** [comment]
Ok I see, you could just use the `ReturnType` utility class from typescript to achieve exactly that what you just described:

```typescript
import hirestime from 'hirestime'

type Elapsor = ReturnType<typeof hirestime>

function something(elapsor: Elapsor) {
  console.log(`${elapsor.seconds()} seconds have passed`)
}

const getElapsed = hirestime()

setTimeout(() => {
  something(getElapsed)
}, 3000)
```

**Comment by emzeidan** [comment]
Wonderful, thank you! I think we can close this issue (and the PR) 🙂

**Comment by seriousManual** [comment]
you're very welcome!
